package entities;

import map.GameMap;

public class Bullet {
    private double x, y;
    private double rotation;
    private double speed;
    private int damage;
    private TypeOfBullet type;

    private int activationDelayMillis;
    private int creationTimeMillis;

    private Player owner;
    private Player target;

    public Bullet(Player target, Player owner, TypeOfBullet type, double rotation, double x, double y) {
        this.target = target;
        this.owner = owner;
        this.type = type;
        this.rotation = rotation;
        this.y = y;
        this.x = x;
        this.creationTimeMillis = (int) System.currentTimeMillis();
        if (type == TypeOfBullet.BASIC) {
            this.speed = 0.15;
            this.damage = 29;
        } else if (type == TypeOfBullet.ROCKET) {
            this.speed = 0.04;
            this.damage = 22;
            this.activationDelayMillis = 1000;
        }
    }

    /**
     * Generated by Gemini AI
     * @param map
     */
    public void move(GameMap map) {
        double moveX = speed * Math.cos(Math.toRadians(rotation));
        double moveY = speed * Math.sin(Math.toRadians(rotation));

        double radius = 0.2;

        double nextX = x + moveX;
        double nextY = y + moveY;

        // 2. Kontrola kolizí (3x3 mřížka)
        int startX = (int) Math.floor(nextX - radius);
        int endX   = (int) Math.floor(nextX + radius);
        int startY = (int) Math.floor(nextY - radius);
        int endY   = (int) Math.floor(nextY + radius);

        for (int ty = startY; ty <= endY; ty++) {
            for (int tx = startX; tx <= endX; tx++) {
                if (tx >= 0 && ty >= 0 && tx < map.getWidth() && ty < map.getHeight()) {
                    if (map.getMapArray()[tx][ty] instanceof blocksOnMap.Wall) {
                        double blockCenterX = tx + 0.5;
                        double blockCenterY = ty + 0.5;
                        if (Math.hypot(nextX - blockCenterX, nextY - blockCenterY) < radius + 0.5) {
                            detonate(map);
                            System.out.println("Bullet hit a wall at (" + tx + ", " + ty + ")");
                        }
                    }
                }
            }
        }if (Math.hypot(target.getX() - nextX, target.getY() - nextY) < radius + 0.4) {
            target.decreaseHealth(damage);
            detonate(map);
            System.out.println("Hit! Target health: " + target.getHealth());
        }

        this.x = nextX;
        this.y = nextY;
    }

    private void detonate(GameMap map) {
        //TODO: create explosion effect
        map.getBullets().remove(this);
    }

    public void turn(){
        int timeFromLaunch = (int) (System.currentTimeMillis() - creationTimeMillis);
        if (type == TypeOfBullet.ROCKET && timeFromLaunch > activationDelayMillis) {
            double targetAngle = Math.atan2(target.getY() - y, target.getX() - x);
            double currentAngle = Math.toRadians(rotation);
            double angleDiff = targetAngle - currentAngle;
            angleDiff = Math.atan2(Math.sin(angleDiff), Math.cos(angleDiff));
            double turnRate = 0.02;
            if (Math.abs(angleDiff) < turnRate) {
                rotation = Math.toDegrees(targetAngle);
            } else {
                rotation += Math.toDegrees(Math.signum(angleDiff) * turnRate);
            }
        }
    }

    public double getX() {
        return x;
    }

    public double getY() {
        return y;
    }
}
