package entities;

import map.GameMap;


/**
 * Represents a tank player in the game.
 * Handles movement, rotation, firing, and health.
 */
public class Player {
    /**
     * Current health of the player.
     */
    private int health;
    /**
     * Maximum health the player can have.
     */
    private int maxHealth;

    private int maxBullets;
    private int currentBullets;

    private int maxRockets;
    private int currentRockets;

    /**
     * Maximum speed the tank can reach.
     */
    private double maxSpeed;
    /**
     * Current speed of the tank.
     */
    private double speed;

    /**
     * The rotation angle of the tank body.
     */
    private double rotation;

    /**
     * The rotation angle of the tank turret.
     */
    private double turretRotation;

    /**
     * Minimum delay between shots in milliseconds.
     */
    private long fireDelayMillis;

    /**
     * Time when the last bullet was fired.
     */
    private long lastBulletFiredMillis;

    private double x;
    private double y;


    /**
     * The frames per second, used for frame-independent movement.
     */
    private int fps;

    /**
     * Creates a new player at the given position.
     * Used at the start of the game.
     *
     * @param x the starting x position
     * @param y the starting y position
     */
    public Player(double x, double y) {
        this.y = y;
        this.x = x;
        this.maxHealth = 100;
        this.health = maxHealth;
        this.maxSpeed = 0.03;
        this.fireDelayMillis = 1000;
        this.currentBullets = 15;
        this.currentRockets = 3;
        this.maxRockets = 3;
        this.maxBullets = 15;
    }

    /**
     * Moves the player, checking for collisions with walls and stopping if hitting them.
     * Generated by Gemini AI
     *
     * @param map the game map to check collisions against
     */
    public void move(GameMap map) {
        // 1. Předpokládaný pohyb
        double moveX = speed * Math.cos(Math.toRadians(rotation));
        double moveY = speed * Math.sin(Math.toRadians(rotation));

        // Radius 0.4 zajistí, že tank neuvízne v úzkých prostorech (čtverec má 1.0)
        double radius = 0.4;

        double nextX = x + moveX;
        double nextY = y + moveY;

        // 2. Kontrola kolizí (3x3 mřížka)
        int startX = (int) Math.floor(nextX - radius);
        int endX = (int) Math.floor(nextX + radius);
        int startY = (int) Math.floor(nextY - radius);
        int endY = (int) Math.floor(nextY + radius);

        boolean hasCollision = false;
        for (int ty = startY; ty <= endY; ty++) {
            for (int tx = startX; tx <= endX; tx++) {
                if (tx >= 0 && ty >= 0 && tx < map.getWidth() && ty < map.getHeight()) {
                    if (map.getMapArray()[tx][ty] instanceof blocksOnMap.Wall) {
                        hasCollision = true;

                        double closestX = clamp(nextX, tx, tx + 1.0);
                        double closestY = clamp(nextY, ty, ty + 1.0);

                        double distX = nextX - closestX;
                        double distY = nextY - closestY;
                        double distanceSquared = (distX * distX) + (distY * distY);

                        if (distanceSquared < radius * radius && distanceSquared > 0) {
                            double distance = Math.sqrt(distanceSquared);
                            double overlap = radius - distance;

                            // Odtlačení od zdi
                            nextX += (distX / distance) * overlap;
                            nextY += (distY / distance) * overlap;
                        }
                    }
                }
            }
        }

        // 3. Finální pozice
        this.x = nextX;
        this.y = nextY;

        // Pokud došlo ke kolizi, snižte rychlost
        if (hasCollision) {
            speed *= 0.95; // Snížit rychlost na polovinu při nárazu do zdi
        }

        // Plynulé zastavení (tření)
        speed *= 0.9;
        if (Math.abs(speed) < 0.0001) speed = 0;
    }

    /**
     * Clamps a value between min and max.
     *
     * @param value the value to clamp
     * @param min   the minimum
     * @param max   the maximum
     * @return the clamped value
     */
    private double clamp(double value, double min, double max) {
        return Math.max(min, Math.min(max, value));
    }


    /**
     * Fires a bullet from the tank.
     * Checks the fire delay before shooting.(must be larger than fireDelayMillis)
     * Checks if the player has bullets left before shooting.
     * @param map    the game map
     * @param owner  this player
     * @param target the other player to target
     */
    public void fireBullet(GameMap map, Player owner, Player target) {
        if (System.currentTimeMillis() - lastBulletFiredMillis > fireDelayMillis) {
            if (currentBullets > 0) {
                removeOneBullet();
                lastBulletFiredMillis = System.currentTimeMillis();
                double spawnX = x + Math.cos(Math.toRadians(turretRotation)) / 3;
                double spawnY = y + Math.sin(Math.toRadians(turretRotation)) / 3;
                map.addBullet(new Bullet(target, owner, TypeOfBullet.BASIC, turretRotation, spawnX, spawnY));
            }
        }
    }
    /**
     * Fires a rocket from the tank.
     * Checks the fire delay before shooting.(must be larger than fireDelayMillis)
     * Checks if the player has rockets left before shooting.
     * @param map    the game map
     * @param owner  this player
     * @param target the other player to target
     */
    public void fireRocket(GameMap map, Player owner, Player target) {
        if (System.currentTimeMillis() - lastBulletFiredMillis > fireDelayMillis) {
            if (currentRockets > 0) {
                removeOneRocket();
                lastBulletFiredMillis = System.currentTimeMillis();
                double spawnX = x + Math.cos(Math.toRadians(turretRotation)) / 3;
                double spawnY = y + Math.sin(Math.toRadians(turretRotation)) / 3;
                map.addBullet(new Bullet(target, owner, TypeOfBullet.ROCKET, turretRotation, spawnX, spawnY));
            }
        }
    }

    /**
     * Speeds up the tank forward.
     */
    public void accelerate() {
        if (fps == 0) {
            fps = 50;
            throw new RuntimeException("FDS is not setted, now setted to default 50");
        }
        //acceleration rate in one sec
        double acceleration = 0.2 / fps;
        if (speed < maxSpeed) {
            speed += acceleration;
        } else {
            speed = maxSpeed;
        }

    }

    /**
     * Slows down or moves the tank backward.
     */
    public void decelerate() {
        if (fps == 0) {
            fps = 50;
            throw new RuntimeException("FDS is not setted, now setted to default 50");
        }
        //acceleration rate in one sec
        double acceleration = 0.2 / fps;
        if (speed > -maxSpeed / 2) {
            speed -= acceleration;
        } else {
            speed = -maxSpeed / 2;
        }
    }

    /**
     * Rotates the tank left.
     */
    public void rotateTankLeft() {
        if (fps == 0) {
            fps = 50;
            throw new RuntimeException("FDS is not setted, now setted to default 50");
        }
        //rotated degrees in one second.
        rotation -= 80. / fps;
    }

    /**
     * Rotates the tank right.
     */
    public void rotateTankRight() {
        if (fps == 0) {
            fps = 50;
            throw new RuntimeException("FDS is not setted, now setted to default 50");
        }
        //rotated degrees in one second.
        rotation += 80. / fps;
    }

    /**
     * Rotates the turret left.
     */
    public void rotateTurretLeft() {
        if (fps == 0) {
            fps = 50;
            throw new RuntimeException("FDS is not setted, now setted to default 50");
        }
        //rotated degrees in one second.
        turretRotation -= 80. / fps;
    }

    /**
     * Rotates the turret right.
     */
    public void rotateTurretRight() {
        if (fps == 0) {
            fps = 50;
            throw new RuntimeException("FDS is not setted, now setted to default 50");
        }
        //rotated degrees in one second.
        turretRotation += 80. / fps;
    }

    /**
     * Reduces the player's health.
     *
     * @param health amount of health to remove
     */
    public void decreaseHealth(int health) {
        if (this.health - health < 0) {
            this.health = 0;
        } else {
            this.health -= health;
        }
    }

    /**
     * Removes one bullet from player.
     * Used after fire.
     */
    private void removeOneBullet() {
        if (currentBullets > 0) {
            currentBullets--;
        }
    }

    /**
     * Removes one rocket from player.
     * Used after fire.
     */
    public void removeOneRocket() {
        if (currentRockets > 0) {
            currentRockets--;
        }
    }

    public void setMaxBullets(int maxBullets) {
        this.maxBullets = maxBullets;
    }

    public void setCurrentBullets(int currentBullets) {
        this.currentBullets = currentBullets;
    }

    public void setMaxRockets(int maxRockets) {
        this.maxRockets = maxRockets;
    }

    public void setCurrentRockets(int currentRockets) {
        this.currentRockets = currentRockets;
    }

    public int getMaxBullets() {
        return maxBullets;
    }

    public int getCurrentBullets() {
        return currentBullets;
    }

    public int getMaxRockets() {
        return maxRockets;
    }

    public int getCurrentRockets() {
        return currentRockets;
    }

    public int getHealth() {
        return health;
    }


    public int getMaxHealth() {
        return maxHealth;
    }


    public double getMaxSpeed() {
        return maxSpeed;
    }


    public double getSpeed() {
        return speed;
    }


    public double getRotation() {
        return rotation;
    }


    public double getTurretRotation() {
        return turretRotation;
    }


    public double getX() {
        return x;
    }


    public double getY() {
        return y;
    }


    public void setFps(int fps) {
        this.fps = fps;
    }

}
