package entities;

import map.GameMap;


public class Player {
    private int health;
    private int maxHealth;

    private double maxSpeed;
    private double speed;

    private double rotation;
    private double turretRotation;

    private double x;
    private double y;

    private int fps;

    public Player(double x,double y) {
        this.y = y;
        this.x = x;
        this.maxHealth = 100;
        this.health = maxHealth;
        this.maxSpeed = 0.03;
    }

    /**
     * Generated by Gemini AI
     * @param map
     */
    public void move(GameMap map) {
        // 1. Předpokládaný pohyb
        double moveX = speed * Math.cos(Math.toRadians(rotation));
        double moveY = speed * Math.sin(Math.toRadians(rotation));

        // Radius 0.4 zajistí, že tank neuvízne v úzkých prostorech (čtverec má 1.0)
        double radius = 0.4;

        double nextX = x + moveX;
        double nextY = y + moveY;

        // 2. Kontrola kolizí (3x3 mřížka)
        int startX = (int) Math.floor(nextX - radius);
        int endX   = (int) Math.floor(nextX + radius);
        int startY = (int) Math.floor(nextY - radius);
        int endY   = (int) Math.floor(nextY + radius);

        boolean hasCollision = false;
        for (int ty = startY; ty <= endY; ty++) {
            for (int tx = startX; tx <= endX; tx++) {
                if (tx >= 0 && ty >= 0 && tx < map.getWidth() && ty < map.getHeight()) {
                    if (map.getMapArray()[tx][ty] instanceof blocksOnMap.Wall) {
                        hasCollision = true;

                        double closestX = clamp(nextX, tx, tx + 1.0);
                        double closestY = clamp(nextY, ty, ty + 1.0);

                        double distX = nextX - closestX;
                        double distY = nextY - closestY;
                        double distanceSquared = (distX * distX) + (distY * distY);

                        if (distanceSquared < radius * radius && distanceSquared > 0) {
                            double distance = Math.sqrt(distanceSquared);
                            double overlap = radius - distance;

                            // Odtlačení od zdi
                            nextX += (distX / distance) * overlap;
                            nextY += (distY / distance) * overlap;
                        }
                    }
                }
            }
        }

        // 3. Finální pozice
        this.x = nextX;
        this.y = nextY;

        // Pokud došlo ke kolizi, snižte rychlost
        if (hasCollision) {
            speed *= 0.95; // Snížit rychlost na polovinu při nárazu do zdi
        }

        // Plynulé zastavení (tření)
        speed *= 0.9;
        if (Math.abs(speed) < 0.0001) speed = 0;
    }

    // Pomocná funkce pro omezení hodnoty mezi min a max
    private double clamp(double value, double min, double max) {
        return Math.max(min, Math.min(max, value));
    }

    public void accelerate() {
        if(fps == 0){
            fps = 50;
            throw new RuntimeException("FDS is not setted, setted to default 50");
        }
        //acceleration rate in one sec
        double acceleration =  0.2/fps;
        if (speed < maxSpeed) {
            speed += acceleration;
        } else {
            speed = maxSpeed;
        }

    }

    public void decelerate() {
        if(fps == 0){
            fps = 50;
            throw new RuntimeException("FDS is not setted, setted to default 50");
        }
        //acceleration rate in one sec
        double acceleration =  0.2/fps;
        if (speed > -maxSpeed / 2) {
            speed -= acceleration;
        } else {
            speed = -maxSpeed / 2;
        }
    }


    public void rotateTankLeft() {
        if(fps == 0){
            fps = 50;
            throw new RuntimeException("FDS is not setted, setted to default 50");
        }
        //rotated degrees in one second.
        rotation -= 80./fps;
    }
    public void rotateTankRight() {
        if(fps == 0){
            fps = 50;
            throw new RuntimeException("FDS is not setted, setted to default 50");
        }
        //rotated degrees in one second.
        rotation += 80./fps;
    }
    public void rotateTurretLeft() {
        if(fps == 0){
            fps = 50;
            throw new RuntimeException("FDS is not setted, setted to default 50");
        }
        //rotated degrees in one second.
        turretRotation -= 80./fps;
    }
    public void rotateTurretRight() {
        if(fps == 0){
            fps = 50;
            throw new RuntimeException("FDS is not setted, setted to default 50");
        }
        //rotated degrees in one second.
        turretRotation += 80./fps;
    }


    public int getHealth() {
        return health;
    }

    public int getMaxHealth() {
        return maxHealth;
    }

    public double getMaxSpeed() {
        return maxSpeed;
    }

    public double getSpeed() {
        return speed;
    }

    public double getRotation() {
        return rotation;
    }

    public double getTurretRotation() {
        return turretRotation;
    }

    public double getX() {
        return x;
    }

    public double getY() {
        return y;
    }

    public void setFps(int fps) {
        this.fps = fps;
    }
}
