package settings;


import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.*;
import java.nio.charset.StandardCharsets;


/**
 * Manages loading and saving game settings.
 * Handles JSON serialization/deserialization of config.
 */
public class ConfigManager {
    /** The current game settings. */
    private static Settings settings;

    /**
     * Loads game settings from a JSON file.
     * @param resourcePath the path to the resource file
     */
    public static void loadGameSettingsResources(String resourcePath) {
        Gson gson = new Gson();
        try (InputStream is = Settings.class.getClassLoader().getResourceAsStream(resourcePath)) {
            if (is == null) {
                throw new RuntimeException("Soubor nebyl nalezen v resources: " + resourcePath);
            }
            try (Reader rd = new InputStreamReader(is, StandardCharsets.UTF_8)) {
                settings = gson.fromJson(rd, Settings.class);
            }
        } catch (Exception e) {
            throw new RuntimeException("Chyba při načítání JSON: " + e.getMessage());
        }
    }

    /**
     * Saves game settings to a JSON file.
     * Generated by Gemini AI
     * @param resourcePath the path to save to
     */
    public static void saveGameSettingsResources(String resourcePath) {
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        try(BufferedWriter bw = new BufferedWriter(new FileWriter("res/"+resourcePath))) {
            gson.toJson(settings,bw);
        }catch (IOException e){
            throw new RuntimeException("Chyba při načítání JSON: " + e.getMessage());
        }
    }

    /**
     * Resets settings to defaults by loading and saving.
     * @param defaultSettingsPath path to default settings file
     * @param settingsPath path to save the reset settings to
     */
    public static void resetToDefaultSettings(String defaultSettingsPath, String settingsPath) {
        loadGameSettingsResources(defaultSettingsPath);
        saveGameSettingsResources(settingsPath);
    }

    public static Settings getSettings() {
        return settings;
    }

}
