package ui.rowsSettings;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * A row for setting key bindings.
 * Shows a button that listens for key presses to update the key code value.
 * Generated by Gemini AI
 */
public class KeyButtonRow extends SettingRowPanel {

    /**
     * Creates a key button row.
     * @param displayName the label text
     * @param valueReference the key code to store
     */
    public KeyButtonRow(String displayName, AtomicInteger valueReference) {
        super(displayName);

        JButton keyButton = new JButton(KeyEvent.getKeyText(valueReference.get()));
        this.add(keyButton, BorderLayout.EAST);
        keyButton.setForeground(new Color(189, 189, 189));
        keyButton.setBorder(BorderFactory.createLineBorder(new Color(0,0,0)));
        keyButton.setBackground(new Color(42, 66, 31));
        keyButton.setPreferredSize(new Dimension(75, 50));

        keyButton.addActionListener(e -> {
            keyButton.setText("...");
            keyButton.requestFocusInWindow();
        });

        keyButton.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (keyButton.getText().equals("...")) {
                    int newKeyCode = e.getKeyCode();

                    valueReference.set(newKeyCode);

                    keyButton.setText(KeyEvent.getKeyText(newKeyCode));

                    requestFocusInWindow();
                }
            }
        });
    }

}
