package ui.rowsSettings;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class KeyButtonRow extends SettingRowPanel {

    /**
     * Generated by Gemini AI
     * @param displayName
     * @param currentKeyCode
     */
    public KeyButtonRow(String displayName, int currentKeyCode) {
        super(displayName);

        JButton keyButton = new JButton(KeyEvent.getKeyText(currentKeyCode));
        this.add(keyButton, BorderLayout.EAST);

        keyButton.addActionListener(e -> {
            keyButton.setText("...");
            keyButton.requestFocusInWindow();
        });

        keyButton.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (keyButton.getText().equals("...")) {
                    int newKeyCode = e.getKeyCode();

                    // 1. Uložíš si newKeyCode do nastavení hry
                    System.out.println("Akce změněna na: " + newKeyCode);

                    keyButton.setText(KeyEvent.getKeyText(newKeyCode));

                    requestFocusInWindow();
                }
            }
        });
    }

}
