package ui.rowsSettings;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.concurrent.atomic.AtomicInteger;

public class KeyButtonRow extends SettingRowPanel {

    /**
     * Generated by Gemini AI
     * @param displayName
     */
    public KeyButtonRow(String displayName, AtomicInteger valueReference) {
        super(displayName);

        JButton keyButton = new JButton(KeyEvent.getKeyText(valueReference.get()));
        this.add(keyButton, BorderLayout.EAST);

        keyButton.addActionListener(e -> {
            keyButton.setText("...");
            keyButton.requestFocusInWindow();
        });

        keyButton.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (keyButton.getText().equals("...")) {
                    int newKeyCode = e.getKeyCode();

                    valueReference.set(newKeyCode);

                    keyButton.setText(KeyEvent.getKeyText(newKeyCode));

                    requestFocusInWindow();
                }
            }
        });
    }

}
